### ISSUE TITLE
Add serde versioned derive

### ISSUE THREAD

**Issue by jam1garner** [doctorn/obake#2]
The main use I'd have for this crate is to version config files (as described in the readme) but there doesn't currently appear to be a mechanism for attempting to attempt to parse as any version (in order to then upgrade it).

Currently it requires something along the lines of:
```rust
let x: Foo  = toml::from_str(content)
    .map(<Foo as obake::Versioned>::Versioned::Foo_v0_2_0)
    .or_else(|_| {
        toml::from_str(content)
            .map(<Foo as obake::Versioned>::Versioned::Foo_v0_1_0)
    })?
    .into();
```

This ofc gets a bit repetitive (the above is only 2 versions!) and while it would require a bit of special-casing, it'd be preferable for the above to be possible to derive serde traits for the Versioned enum.

Alternatively you could provide a mechanism for running a function polymorphic over its return type over each version in sequence until one returns `Ok`.

This could look something like:

```rust
let x = Foo::for_all_versions(toml::from_str)(content)?;
```

Also worth noting (as I'm sure you're away) that if you derive serde traits for the enum using `#[obake(derive(Serialize, Deserialize))]` it will ofc expect you to describe an version such as:

```toml
[Foo_v0_1_0]
foo = 'foo'
baz = 'x'
```

**Comment by doctorn** [comment]
I've added some new helper methods which I think could help implement this. Particularly `try_from_versioned`. Have a look and see what you think?
